var TopLevel = {
"$" : function () {},
"arc" : function () {},
"centroid" : function () {},
"console" : function () {},
"d3" : function () {},
"document" : function () {},
"domain" : function () {},
"dropdown" : function () {},
"format" : function () {},
"getElementById" : function () {},
"Intl" : function () {},
"isNaN" : function () {},
"JSON" : function () {},
"log" : function () {},
"Math" : function () {},
"NumberFormat" : function () {},
"parseFloat" : function () {},
"parseInt" : function () {},
"PI" : function () {},
"pow" : function () {},
"range" : function () {},
"round" : function () {},
"scaleLinear" : function () {},
"stringify" : function () {},
"target" : function () {},
"value" : function () {}
}
